ARG ONEAPI_VERSION=2025.3.3-0-devel-ubuntu24.04

FROM docker.io/intel/deep-learning-essentials:$ONEAPI_VERSION

RUN apt update \
  && add-apt-repository -y ppa:deadsnakes/ppa \
  && apt install -y python3.11

RUN ln -sT /usr/bin/python3.11 /usr/bin/python \
  && wget https://bootstrap.pypa.io/get-pip.py \
  && python3.11 get-pip.py

WORKDIR /llama.cpp/
RUN pip install --index-url https://download.pytorch.org/whl/cpu torch==2.2.0 \
  && pip install --pre ipex-llm[cpp] \
  && init-llama-cpp 

COPY tools.sh .

RUN apt autoremove --yes \
    && apt clean --yes \
    && rm --recursive --force /tmp/* /var/tmp/* \
    && find /var/cache/apt/archives /var/lib/apt/lists -not -name lock -type f -delete \
    && find /var/cache -type f -delete

ENTRYPOINT ["/llama.cpp/tools.sh"]
