services:
  llama.cpp-ipex-qwen2.5-coder-14b:
    image: "localhost/llama.cpp-ipex"
    command: "--server --host 0.0.0.0 --port 8080 --model /models/Qwen2.5-Coder-14B-Instruct-Q4_K_M.gguf --n-gpu-layers 99 --ctx-size 16384 --batch-size 1024 --parallel 1 --jinja"
    volumes:
      - "/home/davi/AI/models/:/models/"
    ports:
      - "8084:8080"
    devices:
      - "/dev/dri/renderD128"
