services:
  searxng:
    image: "docker.io/searxng/searxng:latest"
    volumes:
      - "./searxng/settings.yml:/etc/searxng/settings.yml"
      - "searxng:/var/cache/searxng/"
    ports:
      - "8082:8080"

volumes:
  searxng:
